source/SGU_C2CStore/Controllers/AuctionController.cs
using Microsoft.AspNet.Identity;
using PagedList;
using SGU_C2CStore.Models;
using System;
using System.Collections.Generic;
using System.Data.Entity;
using System.IO;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;

namespace SGU_C2CStore.Controllers
{
    public class AuctionController : Controller
    {
        public string currentURL;
        private ApplicationDbContext db = new ApplicationDbContext();
        // GET: Auction
        public ActionResult Index(string sortOrder, int? page, string search, string currentSearch, int? catId, int? currentcateId)
        {
            ViewBag.Forgot = new ForgotPasswordViewModel();
            ViewBag.Login = new LoginViewModel();
            ViewBag.Register = new RegisterViewModel();
            List<Category> category = db.Categories.ToList();
            ViewBag.Category = category;
            ViewBag.Avatar = db.Photos.ToList();

            //var all = db.Products.Where(p => p.ProductStatus == ProductStatus.Selling);
            var auctions = db.AuctionProducts.Where(p => p.ProductStatus == ProductStatus.Selling);
            //var auc = all.Except(auction);
            //var auctions = all.Except(auc);
           
            if (search != null)
            {
                page = 1;
            }
            else
            {
                search = currentSearch;
            }

            ViewBag.CurrentSort = sortOrder;
            if (!string.IsNullOrEmpty(search))
            {
                auctions = auctions.Where(p => p.Name.Contains(search) || p.Name.StartsWith(search));
            }
            ViewBag.CurrentSearch = search;

            if (catId == 0 || catId == null)
            {
                auctions = auctions.Where(p => p.CategoryId != catId); ;
            }
            else
            {
                auctions = auctions.Where(p => p.CategoryId == catId);
            }
            ViewBag.CurrentFilter = catId;
            ViewBag.NameSort = String.IsNullOrEmpty(sortOrder) ? "name_desc" : "";
            ViewBag.DateSort = sortOrder == "Date" ? "date_desc" : "Date";
            ViewBag.PriceSort = sortOrder == "Price" ? "Price_desc" : "Price";
            switch (sortOrder)
            {
                case "date_desc":
                    auctions = auctions.OrderByDescending(p => p.DateCreate);
                    break;
                case "name_desc":
                    auctions = auctions.OrderByDescending(p => p.Name);
                    break;
                case "Name":
                    auctions = auctions.OrderBy(p => p.Name);
                    break;
                case "Price":
                    auctions = auctions.OrderBy(p => p.Price);
                    break;
                case "Price_desc":
                    auctions = auctions.OrderByDescending(p => p.Price);
                    break;
                default:
                    auctions = auctions.OrderBy(p => p.DateCreate);
                    break;
            }

            int pageSize = 9;
            int pageNumber = (page ?? 1);
            return View(auctions.ToPagedList(pageNumber, pageSize));
        }
        public ActionResult Create()
        {

            IEnumerable<SelectListItem> items = db.Categories.Select(
                c => new SelectListItem
                {
                    Value = c.Id.ToString(),
                    Text = c.Name
                });

            ViewBag.CategoryId = items;
            AuctionProduct auctions = new AuctionProduct();

            return View();
        }
        [HttpPost]
        [Authorize]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "Id,Name,CategoryId,Price,Description,UserId,CurrentPrice,")] AuctionProduct auctions, IEnumerable<HttpPostedFileBase> upload)
        {
            
            var userId = User.Identity.GetUserId();
            ApplicationUser user = db.Users.SingleOrDefault(e => e.Id == userId);
            if (ModelState.IsValid)
            {
                foreach (var item in upload)
                {
                    Photo photo = new Photo();
                    if (item.ContentLength > 0)
                    {

                        string extension = Path.GetExtension(item.FileName);
                        var path = Path.Combine(Server.MapPath("~/Images"), auctions.Id + extension);
                        item.SaveAs(path);
                        photo.URL = auctions.Id + extension;
                        photo.Product = db.AuctionProducts.SingleOrDefault(e => e.Id == auctions.Id);

                        db.Photos.Add(photo);
                    }
                }
                auctions.User = user;
                auctions.UserId = userId;
                auctions.DateCreate = DateTime.Now;
                auctions.ProductStatus = ProductStatus.Selling;             
                auctions.CurrentPrice = auctions.Price;
                auctions.EndTime = DateTime.Now;
                auctions.StartTime = DateTime.Now;
                db.AuctionProducts.Add(auctions);
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            IEnumerable<SelectListItem> items = db.Categories.Select(
                c => new SelectListItem
                {
                    Value = c.Id.ToString(),
                    Text = c.Name

                });
            ViewBag.Login = new LoginViewModel();
            ViewBag.Register = new RegisterViewModel();
            ViewBag.Forgot = new ForgotPasswordViewModel();
            ViewBag.CategoryId = items;
            return View(auctions);
        }
        // GET: Products/Details/5
        public ActionResult Details(int? id)
        {
            AuctionProduct auction = db.AuctionProducts.Find(id);
            if (id == null )
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }          
            if (auction == null)
            {
                return HttpNotFound();
            }
            ViewBag.Images = db.Photos.Where(i => i.ProductId == id).ToList();
            ViewBag.Login = new LoginViewModel();
            ViewBag.Register = new RegisterViewModel();
            ViewBag.Forgot = new ForgotPasswordViewModel();
            ViewBag.AuctionId = id;
            currentURL = Request.Url.AbsoluteUri;
            List<Category> category = db.Categories.ToList();
            ViewBag.Category = category;
            return View(auction);
        }
        public void Stop(int id)
        {
            AuctionProduct auction = db.AuctionProducts.Find(id);
            auction.ProductStatus = ProductStatus.Sold;
            db.Entry(auction).State = EntityState.Modified;
            db.SaveChanges();
        }
    }
}

source/SGU_C2CStore/Views/Auction/Create.cshtml
@model SGU_C2CStore.Models.AuctionProduct

@{
    ViewBag.Title = "Create";
    Layout = "~/Views/Shared/_AccountLayout.cshtml";

}


@using (Html.BeginForm("Create", "Auction", FormMethod.Post, new { enctype = "multipart/form-data" }))
{
    @Html.AntiForgeryToken()
    <section class="span9">

        <div class="underlined push-down-20">
            <div class="row">
                <div class="span4">
                    <h3><span class="light">Create</span> Auction</h3>
                </div>
                <div class="span5 align-right sm-align-left">

                </div>
            </div>
        </div>


        <div class="row blocks-spacer">

            <div class="span3">
                <input type="file" class="multi" name="upload" id="Avartar" maxlength="5" accept="gif|jpg|png" />
                First Images is avatar
            </div>



            <div class="span6">
                <div class="product-title">
                    @Html.EditorFor(model => model.Name, new { htmlAttributes = new { placeholder = "Your Product Name", @class = "span5" } })

                    <div class="meta">
                        @Html.EditorFor(model => model.Price, new { htmlAttributes = new { placeholder = "Your Product Price", @class = "span5" } })
                    </div>
                    <div class="meta">
                        @Html.LabelFor(model => model.CategoryId, "CategoryId", htmlAttributes: new { @class = "control-label col-md-2" })
                        &nbsp;
                        @Html.DropDownList("CategoryId", (IEnumerable<SelectListItem>)ViewBag.Categories, htmlAttributes: new { @class = "form-control" })
                        @Html.ValidationMessageFor(model => model.CategoryId, "", new { @class = "text-danger" })
                    </div>
                </div>


                <div class="product-description">
                    @Html.LabelFor(model => model.Description, "Description", htmlAttributes: new { @class = "control-label col-md-2" })
                    @Html.EditorFor(model => model.Description, new { htmlAttributes = new { placeholder = "Your Product Price", @class = "span5" } })




                    <form action="#" class="form form-inline clearfix">


                        <input type="submit" value="Create" class="btn btn-danger pull-right" />
                    </form>
                    <hr />

                </div>
            </div>
        </div>


    </section>
}
@section scripts {
    <script src="/Assets/user/js/jquery-1.10.2.min.js" type="text/javascript" language="javascript"></script>
    <script src="/Assets/user/js/jquery.MultiFile.js" type="text/javascript" language="javascript"></script>
}

source/SGU_C2CStore/Views/Auction/Details.cshtml
@model SGU_C2CStore.Models.AuctionProduct
@using SGU_C2CStore.Models
@{
    Photo photo = new Photo();
    List<Photo> list = ViewBag.Images;
    ViewBag.Title = "Details";
    var auctionID = ViewBag.Auction;
    Layout = "~/Views/Shared/_ProductsLayout.cshtml";
    string URL = Request.Url.AbsoluteUri;
    ApplicationDbContext db = new ApplicationDbContext();
    var Category = db.Categories.FirstOrDefault(p => p.Id == Model.CategoryId);
}

<script src="~/Scripts/jquery-2.1.4.js"></script>
<script src="~/Scripts/jquery.signalR-2.2.0.js"></script>
<script src="~/signalr/hubs"></script>


<section class="span9">
    <div class="underlined push-down-20">
        <div class="row">
            <div class="span4">
                <h3><span class="light">Detail</span> Product</h3>
            </div>
            <div class="span5 align-right sm-align-left">

            </div>
        </div>
    </div>
    <div class="row blocks-spacer">


        <div class="span3">
            <div class="product-preview">
                @for (int i = 0; i < list.Count; i++)
                {
                    if (i == 0)
                    {
                        <div class="picture">
                            <img src="~/Images/@list[i].URL" alt="" width="940" height="940" id="mainPreviewImg" />
                        </div>
                    }
                }

                <div class="thumbs clearfix">
                    @for (int i = 0; i < list.Count; i++)
                    {
                        if (i == 0)
                        {
                            <div class="thumb active">
                                <a href="#mainPreviewImg"><img src="~/Images/@list[i].URL" alt="" width="940" height="940" /></a>
                            </div>
                        }
                        else
                        {
                            <div class="thumb">
                                <a href="#mainPreviewImg"><img src="~/Images/@list[i].URL" alt="" width="940" height="940" /></a>
                            </div>
                        }
                    }
                </div>
            </div>
        </div>



        <div class="span6">
            <div class="product-title">
                <h1 class="name"><span class="light">@Html.DisplayFor(model => model.Name)</span></h1>
                <div class="meta">
                    <span data-itemid="@Model.Id" class="tag">@Html.DisplayFor(model => model.CurrentPrice)</span>
                    
                </div>
            </div>
            <div class="product-description">
                <div class="countdown">
                    <span id="clock"></span>
                </div>
                <div class="span4">
                        @Category.Name
                    <br />
                    <span class="zocial-guest"></span> @Html.DisplayFor(model => model.User.FullName)

                </div>

                <form action="#" class="form form-inline clearfix">
                    <input type="text" id="btnBid" placeholder="Bid Now"/>
                    <button id="@Model.Id" class="btnclass btn btn-danger pull-right">Bid</button>  
                </form>
                <hr />


            </div>
        </div>
    </div>
    <div class="row">
        <div class="span9">
            <ul id="myTab" class="nav nav-tabs">
                <li class="active">
                    <a href="#tab-1" data-toggle="tab">@Html.DisplayNameFor(model => model.Description)</a>
                </li>

            </ul>
            <div class="tab-content">
                <div class="fade in tab-pane active" id="tab-1">
                    <h3>@Html.DisplayFor(model => model.Name)</h3>

                    <p>@Html.DisplayFor(model => model.Description)</p>

                </div>
            </div>
        </div>
    </div>
</section>

@section scripts2 {
    <script src="~/Scripts/jquery-2.1.4.js"></script>
    <script src="~/Scripts/jquery.signalR-2.2.0.js"></script>
    <script src="~/signalr/hubs"></script>
    <script src="~/Scripts/auction.js"></script>
    <script src="~/Scripts/jquery.countdown.js"></script>
<script type="text/javascript">

    var time = '@string.Format("{0:yyyy/MM/dd H:mm:ss}",Model.EndTime)'
    var id = '@Model.Id'
    $('#clock').countdown(time)
     .on('update.countdown', function(event) {
         var format = '%H:%M:%S';
          if(event.offset.days > 0) {
                 format = '%-d day%!d ' + format;
               }
           if(event.offset.weeks > 0) {
                format = '%-w week%!w ' + format;
               }
           $(this).html(event.strftime(format));
         })
    .on('finish.countdown', function(event) {
           $(this).html('Stoped!')
             .parent().addClass('disabled');
           $.post("@Url.Action("Stop","Auction")", { id : id} ,function(data){
               alert(data);
           });
        });

</script>
}

source/SGU_C2CStore/Views/Auction/Index.cshtml
@model PagedList.IPagedList<SGU_C2CStore.Models.AuctionProduct>
@using PagedList.Mvc;
@using PagedList;
<link href="~/Content/PagedList.css" rel="stylesheet" type="text/css" />
@using SGU_C2CStore.Models
@using Microsoft.AspNet.Identity
@{

    Photo photo = new Photo();
    List<Photo> list;
    list = ViewBag.Avatar as List<Photo>;
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_ProductsLayout.cshtml";
    string URL = Request.Url.AbsoluteUri;

}


<section class="span9">

    <div class="underlined push-down-20">
        <div class="row">
            <div class="span4">
                <h3><span class="light">All</span> Products</h3>
            </div>
            <div class="span5 align-right sm-align-left">
                <div class="form-inline sorting-by" id="tourStep4">
                    <label for="isotopeSorting" class="black-clr">Sắp xếp:</label>
                    <label>@Html.ActionLink("  Tên  ", "Index", new { sortOrder = ViewBag.NameSort, currentSearch = ViewBag.CurrentSearch })</label>
                    <label> | </label>
                    <label>@Html.ActionLink("  Giá  ", "Index", new { sortOrder = ViewBag.PriceSort, currentSearch = ViewBag.CurrentSearch })</label>
                    <label> | </label>
                    <label>@Html.ActionLink("  Ngày Đăng  ", "Index", new { sortOrder = ViewBag.DateSort, currentSearch = ViewBag.CurrentSearch })</label>

                </div>
                <div class="view-switch">
                    <a href="shop.html" class="btn btn-primary"><i class="icon-th"></i></a>
                    <a href="shop-list-view.html" class="btn"><i class="icon-list"></i></a>
                </div>
            </div>
        </div>
    </div>


    <div class="row popup-products">
        <div>
            @foreach (var item in Model)
            {
                List<Photo> listPhoto = list.Where(i => i.ProductId == item.Id).ToList();

                <div class="span3">
                    <div class="product">
                        <div class="product-inner">
                            <div class="stamp red">@item.ProductStatus</div>
                            <div class="product-img">
                                <div class="picture">
                                    <a href="product.html"><img width="540" height="374" alt="" src="~/Images/@listPhoto[0].URL" /></a>
                                    <div class="img-overlay">
                                        <a class="btn more btn-primary" href="@Url.Action("Details", new {id =item.Id})">More</a>
                                        @if (Request.IsAuthenticated)
                                        {
                                            if (item.UserId != User.Identity.GetUserId() || !Request.IsAuthenticated)
                                            {
                                                <a class="btn buy btn-danger" href="@Url.Action("AddToCart", "ShoppingCart", new { id = item.Id, returnUrl = URL })">Add to Cart</a>
                                            }
                                            if (item.UserId == User.Identity.GetUserId())
                                            {
                                                <a class="btn buy ">Add to Cart</a>
                                            }
                                        }
                                    </div>
                                </div>
                            </div>
                            <div class="main-titles no-margin">
                                <h4 class="title"><i class="icon-fixed-width">&#xf0e3;</i><span data-itemid="@item.Id">@Html.DisplayFor(modelItem => item.Price)</span></h4>
                                <h5 class="no-margin"><i class="icon-fixed-width">&#xf101;</i>@Html.DisplayFor(modelItem => item.Name)</h5>
                            </div>

                        </div>
                    </div>
                </div>
            }

        </div>
    </div>

    <hr />
    @Html.PagedListPager(Model, page => Url.Action("Index", new { page, sortOrder = ViewBag.CurrentSort, currentSearch = ViewBag.CurrentSearch, currentcateId = ViewBag.CurrentFilter }))
</section>