source/SGU_C2CStore/Controllers/OrdersController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using SGU_C2CStore.Models;
using Microsoft.AspNet.Identity;
using Rotativa;

namespace SGU_C2CStore.Controllers
{
    [Authorize]
    public class OrdersController : Controller
    {
        private ApplicationDbContext db = new ApplicationDbContext();

        // GET: Orders
        public ActionResult Index()
        {
            var orders = db.Orders.Include(o => o.User);
            return View(orders.ToList());
        }

        // GET: Orders/Details/5
        public ActionResult Details(string userId,int orderId)
        {
            ApplicationUser user = db.Users.FirstOrDefault(u => u.Id == userId);
            ViewBag.User = user;
            Order order = db.Orders.Find(orderId);
            List<OrderDetail> details = db.OrderDetails.Where(p => p.OrderId == orderId).ToList();
            ViewBag.Details = details;
            ViewBag.Order = order;
            return View();
        }
        public ActionResult OrderRating()
        {
            ApplicationDbContext db = new ApplicationDbContext();
            string userId = User.Identity.GetUserId();
            ApplicationUser user = db.Users.FirstOrDefault(u => u.Id == userId);
            List<Order> order = db.Orders.Where(i => i.UserId == userId).ToList();
            List<OrderDetail> details = db.OrderDetails.Where(i => i.Order.UserId == userId).ToList();
            ViewBag.ListOrderDetails = details;
            ViewBag.ListOrders = order;
            ViewBag.Account = user;
            return View();
        }
        public ActionResult Rating(string Id, int IdOrder)
        {
            Decimal count = 0;
            int i = 0;
            ApplicationDbContext db = new ApplicationDbContext();
           
            OrderDetail od = db.OrderDetails.FirstOrDefault(o => o.Id == IdOrder);
            switch (Id)
            {
                case "1":
                    od.Rating = 1;
                    db.Entry(od).State = EntityState.Modified;
                    db.SaveChanges();
                    ViewBag.TB = 1;
                    break;
                case "2":
                    od.Rating = 2;
                    db.Entry(od).State = EntityState.Modified;
                    db.SaveChanges();
                    ViewBag.TB = 2;
                    break;
                case "3":
                    od.Rating = 3;
                    ViewBag.TB = 3;
                    db.Entry(od).State = EntityState.Modified;
                    db.SaveChanges();
                    break;
                case "4":
                    od.Rating = 4;
                    ViewBag.TB = 4;
                    db.Entry(od).State = EntityState.Modified;
                    db.SaveChanges();
                    break;
                case "5":
                    od.Rating = 5;
                    ViewBag.TB = 5;
                    db.Entry(od).State = EntityState.Modified;
                    db.SaveChanges();
                    break;
                case "6":
                    od.Rating = 6;
                    ViewBag.TB = 6;
                    db.Entry(od).State = EntityState.Modified;
                    db.SaveChanges();
                    break;
                case "7":
                    od.Rating = 7;
                    ViewBag.TB = 7;
                    db.Entry(od).State = EntityState.Modified;
                    db.SaveChanges();
                    break;
                case "8":
                    od.Rating = 8;
                    ViewBag.TB = 8;
                    db.Entry(od).State = EntityState.Modified;
                    db.SaveChanges();
                    break;
                case "9":
                    od.Rating = 9;
                    ViewBag.TB = 9;
                    db.Entry(od).State = EntityState.Modified;
                    db.SaveChanges();
                    break;
                case "10":
                    od.Rating = 10;
                    ViewBag.TB = 10;
                    db.Entry(od).State = EntityState.Modified;
                    db.SaveChanges();
                    break;
                
            }
                ApplicationUser user = db.Users.FirstOrDefault(p => p.Id == od.Product.User.Id);
                List<OrderDetail> detail = db.OrderDetails.Where(p => p.Product.User.Id == od.Product.User.Id).ToList();
                foreach (OrderDetail item in detail)
                {
                    if (item.Rating != 0)
                    {
                        i++;
                        count = count + item.Rating;
                    }
                }
                if (i != 0)
                {
                    user.Score = count / i;
                    db.SaveChanges();
                }
            return RedirectToAction("OrderRating");
        }
        // GET: Orders/Create

        // POST: Orders/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.


        
        public ActionResult Create()
        {
            var userId = User.Identity.GetUserId();
            // Fetch the userprofile
            ApplicationUser user = db.Users.FirstOrDefault(u => u.Id == userId);
            Order order = new Order();
            List<Product> cart = Session["Cart"] as List<Product>;
            int Total = 0;
            order.ShipAddress = user.Address;
            order.OrderTime = DateTime.Now;
            order.UserId = userId;          
            foreach(Product product in cart)
            {
                Product productdb = db.Products.Find(product.Id);
                Total = Total + product.Price;
                OrderDetail orderDetail = new OrderDetail();
                orderDetail.Product = db.Products.FirstOrDefault(p => p.Id == product.Id);
                orderDetail.ProductPrice = product.Price;
                orderDetail.OrderId = order.Id;
                productdb.ProductStatus = ProductStatus.Sold;           
                db.OrderDetails.Add(orderDetail);
            }
            order.ShipTime= DateTime.Now;
            order.Total = Total;
            order.User = user;
            Session["Cart"] = null;
            db.Orders.Add(order);
            db.SaveChanges();
            return RedirectToAction("Details",new { orderId= order.Id , userId =user.Id});                
        }

        // GET: Orders/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Order order = db.Orders.Find(id);
            if (order == null)
            {
                return HttpNotFound();
            }
            ViewBag.UserId = new SelectList(db.AspNetUsers, "Id", "FullName", order.UserId);
            return View(order);
        }

        // POST: Orders/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "Id,OrderTime,ShipTime,ShipAddress,UserId,Total")] Order order)
        {
            if (ModelState.IsValid)
            {
                db.Entry(order).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.UserId = new SelectList(db.AspNetUsers, "Id", "FullName", order.UserId);
            return View(order);
        }

        // GET: Orders/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Order order = db.Orders.Find(id);
            if (order == null)
            {
                return HttpNotFound();
            }
            return View(order);
        }

        // POST: Orders/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Order order = db.Orders.Find(id);
            db.Orders.Remove(order);
            db.SaveChanges();
            return RedirectToAction("Index");
        }
        public ActionResult ExportPDF(string userId,int orderId)
        {
            return new ActionAsPdf("Details", new { orderId = orderId, userId = userId })
            {
                FileName = Server.MapPath("~/Assets/user/PDF/Invoice.pdf")
            };
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

source/SGU_C2CStore/Controllers/ShoppingCartController.cs
using SGU_C2CStore.Models;
using System.Collections.Generic;
using System.Linq;
using System.Web.Mvc;
using Microsoft.AspNet.Identity;
using System.Data.Entity;
using System.Threading.Tasks;

namespace SGU_C2CStore.Controllers
{
    public class ShoppingCartController : Controller
    {
        ApplicationDbContext db = new ApplicationDbContext();
        
        //
        // GET: /ShoppingCart/
        List<Product> cart;
        Product product = new Product();
        public ActionResult Index()
        {
            return View();
        }
        public ActionResult AddToCart(int id, string returnUrl)
        {
            if (Session["Cart"] == null)
            {
                cart = new List<Product>();
                product = db.Products.Where(i => i.Id == id).Single();
                cart.Add(product);
                Session["Cart"] = cart;
            }
            else
            {
                cart = Session["Cart"] as List<Product>;
                if (!isExist(id))
                {
                    product = db.Products.Where(i => i.Id == id).Single();
                    cart.Add(product);
                }
                Session["Cart"] = cart;
            }
            return RedirectToLocal(returnUrl);
        }
        public bool isExist(int id)
        {
            cart = Session["Cart"] as List<Product>;
            Product isExist = cart.Find(i => i.Id == id);
            if (isExist == null)
            {
                return false;
            }
            else
            {
                return true;
            }

        }
        public ActionResult RemoveFormCart(int id, string returnUrl)
        {
            cart = Session["Cart"] as List<Product>;
            Product product = cart.Find(i => i.Id == id);
            cart.Remove(product);
            Session["Cart"] = cart;
            return RedirectToLocal(returnUrl);
        }
       
        private ActionResult RedirectToLocal(string returnUrl)
        {
            if (returnUrl != null)
            {
                return Redirect(returnUrl);
            }
            return RedirectToAction("Index", "Products");
        }
        [Authorize]
        public ActionResult Checkout()
        {
         
            return View();
        }


    }
}

source/SGU_C2CStore/Views/ShoppingCart/Checkout.cshtml
@using SGU_C2CStore.Models
@{
    Layout = null;
    ApplicationDbContext db = new ApplicationDbContext();
    Photo photo = new Photo();
    List<Photo> list = db.Photos.ToList();
    List<Photo> listphoto;
    int total = 0;
    int count = 0;
    if (Session["Cart"] != null)
    {
        foreach (Product product in (List<Product>)Session["Cart"])
        {
            total = total + 1;
            count = count + product.Price;
        }
    }
    string URL = Request.Url.AbsoluteUri;
}

<!DOCTYPE html>
<!--[if lt IE 8]>      <html class="no-js lt-ie10 lt-ie9 lt-ie8"> <![endif]-->
<!--[if IE 8]>         <html class="no-js lt-ie10 lt-ie9"> <![endif]-->
<!--[if IE 9]>         <html class="no-js lt-ie10"> <![endif]-->
<!--[if gt IE 8]><!-->
<html class="no-js">
<!--<![endif]-->
<!-- Mirrored from www.proteusthemes.com/themes/webmarket-html/checkout-step-1.html by HTTrack Website Copier/3.x [XR&CO'2014], Sun, 09 Aug 2015 15:42:38 GMT -->
<head>
    <meta charset="utf-8">
    <title>Webmarket HTML Template - Checkout Step 1</title>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="description" content="">
    <meta name="author" content="ProteusThemes">

    <script type="text/javascript">
        WebFontConfig = {
            google : {
                families : ['Open+Sans:400,700,400italic,700italic:latin,latin-ext,cyrillic', 'Pacifico::latin']
            }
        };
        (function() {
            var wf = document.createElement('script');
            wf.src = ('https:' == document.location.protocol ? 'https' : 'http') + '://ajax.googleapis.com/ajax/libs/webfont/1/webfont.js';
            wf.type = 'text/javascript';
            wf.async = 'true';
            var s = document.getElementsByTagName('script')[0];
            s.parentNode.insertBefore(wf, s);
        })();
    </script>

    <link href="/Assets/user/stylesheets/bootstrap.css" rel="stylesheet">
    <link href="/Assets/user/stylesheets/responsive.css" rel="stylesheet">

    <link rel="stylesheet" href="/Assets/user/js/rs-plugin/css/settings.css" type="text/css" />

    <link rel="stylesheet" href="/Assets/user/js/jquery-ui-1.10.3/css/smoothness/jquery-ui-1.10.3.custom.min.css" type="text/css" />

    <link rel="stylesheet" href="/Assets/user/js/prettyphoto/css/prettyPhoto.css" type="text/css" />

    <link href="/Assets/user/stylesheets/main.css" rel="stylesheet">

    <script src="/Assets/user/js/modernizr.custom.56918.js"></script>

    <link rel="apple-touch-icon-precomposed" sizes="144x144" href="/Assets/user/images/apple-touch/144.png">
    <link rel="apple-touch-icon-precomposed" sizes="114x114" href="/Assets/user/images/apple-touch/114.png">
    <link rel="apple-touch-icon-precomposed" sizes="72x72" href="/Assets/user/images/apple-touch/72.png">
    <link rel="apple-touch-icon-precomposed" href="/Assets/user/images/apple-touch/57.png">
    <link rel="shortcut icon" href="/Assets/user/images/apple-touch/57.png">
</head>
<body class=" checkout-page">
    <div class="master-wrapper">
        <div class="container">
            <div class="row">



                <section class="span12">
                    <div class="checkout-container">
                        <div class="row">
                            <div class="span10 offset1">



                                <header>
                                    <div class="row">
                                        <div class="span2">
                                            <a href="@Url.Action("Index","Products")"><img src="/Assets/user/images/logo-bw.png" alt="Webmarket Logo" width="48" height="48" /></a>
                                        </div>
                                        <div class="span6">
                                            <div class="center-align">
                                                <h1><span class="light">Review</span> Shopping Cart</h1>
                                            </div>
                                        </div>
                                        <div class="span2">
                                            <div class="right-align">
                                                <img src="/Assets/user/images/buttons/security.jpg" alt="Security Sign" width="92" height="65" />
                                            </div>
                                        </div>
                                    </div>
                                </header>



                                <div class="checkout-steps">
                                    <div class="clearfix">
                                        <div class="step done">
                                            <div class="step-badge">1</div>
                                            Shopping Cart
                                        </div>
                                        <div class="step done">
                                            <div class="step-badge">2</div>
                                            Shipping Address
                                        </div>
                                       
                                        <div class="step active">
                                            <div class="step-badge">3</div>
                                            Confirm
                                        </div>
                                    </div>
                                </div>



                                <table class="table table-items">
                                    <thead>
                                        <tr>
                                            <th colspan="2">Item</th>
                                            <th><div class="align-center">Quantity</div></th>
                                            <th><div class="align-right">Price</div></th>
                                        </tr>
                                    </thead>
                                    <tbody>
                                        @if (Session["Cart"] != null)
                                        {
                                            foreach (Product product in (List<Product>)Session["Cart"])
                                            {
                                                listphoto = list.Where(i => i.ProductId == product.Id).ToList();
                                                <tr>
                                                    <td class="image"><img src="~/Images/@listphoto[0].URL" alt="" width="124" height="124" /></td>
                                                    <td class="desc">@product.Name<a href="@Url.Action("RemoveFormCart", "ShoppingCart", new { id = product.Id, returnUrl = URL})"><i class="icon-fixed-width">&#xf00d;</i></a></td>
                                                    <td class="qty"></td>
                                                    <td class="price">
                                                        @product.Price
                                                    </td>
                                                </tr>
                                            }
                                        }
                                        <tr>
                                            <td colspan="2" rowspan="2">        
                                            </td>
                                            <td class="stronger">Shipping:</td>
                                            <td class="stronger"><div class="align-right">$4.99</div></td>
                                        </tr>
                                        <tr>
                                            <td class="stronger">Subtotal:</td>
                                            <td class="stronger"><div class="size-16 align-right">$357.81</div></td>
                                        </tr>
                                    </tbody>
                                </table>
                                <hr />
                                <p class="right-align">
                                    In the next step you will choose your shipping address &nbsp; &nbsp;
                                    <a href="@Url.Action("Create","Orders")" class="btn btn-primary higher bold">CONTINUE</a>
                                </p>
                            </div>
                        </div>
                    </div>
                </section>
            </div>
        </div>
    </div>




    <div id="fb-root"></div>
    <script>
(function(d, s, id) {
      var js, fjs = d.getElementsByTagName(s)[0];
      if (d.getElementById(id)) return;
      js = d.createElement(s); js.id = id;
      js.src = "../../../connect.facebook.net/en_US/all.html#xfbml=1&appId=126780447403102";
      fjs.parentNode.insertBefore(js, fjs);
    }(document, 'script', 'facebook-jssdk'));</script>

    <script type="text/javascript" src="../../../ajax.googleapis.com/ajax/libs/jquery/1.9.1/jquery.min.html"></script>
    <script type="text/javascript">
    if (typeof jQuery == 'undefined') {
        document.write('<script src="/Assets/user/js/jquery.min.js"><\/script>');
    }
    </script>

    <script src="/Assets/user/js/underscore/underscore-min.js" type="text/javascript"></script>

    <script src="/Assets/user/js/bootstrap.min.js" type="text/javascript"></script>

    <script src="/Assets/user/js/rs-plugin/js/jquery.themepunch.plugins.min.js" type="text/javascript"></script>
    <script src="/Assets/user/js/rs-plugin/js/jquery.themepunch.revolution.min.js" type="text/javascript"></script>

    <script src="/Assets/user/js/jquery.carouFredSel-6.2.1-packed.js" type="text/javascript"></script>

    <script src="/Assets/user/js/jquery-ui-1.10.3/js/jquery-ui-1.10.3.custom.min.js" type="text/javascript"></script>
    <script src="/Assets/user/js/jquery-ui-1.10.3/touch-fix.min.js" type="text/javascript"></script>

    <script src="/Assets/user/js/isotope/jquery.isotope.min.js" type="text/javascript"></script>

    <script src="/Assets/user/js/bootstrap-tour/build/js/bootstrap-tour.min.js" type="text/javascript"></script>

    <script src="/Assets/user/js/prettyphoto/js/jquery.prettyPhoto.js" type="text/javascript"></script>

    <script type="text/javascript" src="http://maps.google.com/maps/api/js?key=AIzaSyDvMjN1g49P1MA2Onsj-GulDkmDuuH6aoU&amp;sensor=false"></script>
    <script type="text/javascript" src="/Assets/user/js/goMap/js/jquery.gomap-1.3.2.min.js"></script>

    <script src="/Assets/user/js/custom.js" type="text/javascript"></script>
</body>
<!-- Mirrored from www.proteusthemes.com/themes/webmarket-html/checkout-step-1.html by HTTrack Website Copier/3.x [XR&CO'2014], Sun, 09 Aug 2015 15:42:43 GMT -->
</html>